// Reliability harness for the dictionary pipeline.
// Measures what the user actually experiences: can I look up a word and get a
// usable entry back? Run it cold (empty cache) to measure the real worst case.
//
//   npx tsx scripts/lookup-harness.ts            # 200 common words, cold cache
//   npx tsx scripts/lookup-harness.ts --warm     # reuse cache (fast path check)
//   npx tsx scripts/lookup-harness.ts --offline  # force network failure; only cache may serve
//   npx tsx scripts/lookup-harness.ts --words 500
//
// Exit code 0 = pass, 1 = fail. Writes docs/lookup-harness-report.md.

import { writeFileSync, mkdirSync } from 'node:fs';
import { fetchWord, probeDictApi, WordNotFound } from '../src/dictionary.js';
import { db } from '../src/db.js';
import { WORDS } from './wordlist.js';

const arg = (name: string) => process.argv.includes(name);
const numArg = (name: string, fallback: number) => {
  const i = process.argv.indexOf(name);
  return i === -1 ? fallback : Number(process.argv[i + 1]) || fallback;
};

const WARM = arg('--warm');
const OFFLINE = arg('--offline');
const LIMIT = numArg('--words', 200);
const PASS_RATE = 0.95;

// A forced-offline run must be served entirely from the persistent cache.
if (OFFLINE) {
  const realFetch = globalThis.fetch;
  globalThis.fetch = (() => Promise.reject(new Error('offline (forced)'))) as typeof fetch;
  process.on('exit', () => { globalThis.fetch = realFetch; });
}

interface Row {
  word: string;
  ok: boolean;
  ms: number;
  source: 'cache' | 'network';
  defs: number;
  hasOrigin: boolean;
  error?: string;
}

const rows: Row[] = [];
// Serial on purpose: the prefetcher paces Wiktionary internally, and a burst
// from the harness would measure our own rate limiting rather than reliability.
for (const word of WORDS.slice(0, LIMIT)) {
  const before = Date.now();
  const hadCache = !!db.prepare('SELECT 1 FROM entries WHERE word = ?').get(word);
  try {
    const entry = await fetchWord(word, 1);
    rows.push({
      word,
      ok: entry.meanings.length > 0 && entry.meanings.some(m => m.definitions.length > 0),
      ms: Date.now() - before,
      source: WARM || hadCache ? 'cache' : 'network',
      defs: entry.meanings.reduce((n, m) => n + m.definitions.length, 0),
      hasOrigin: !!entry.origin,
    });
  } catch (e) {
    rows.push({
      word, ok: false, ms: Date.now() - before,
      source: hadCache ? 'cache' : 'network', defs: 0, hasOrigin: false,
      error: e instanceof WordNotFound ? 'not found' : (e as Error).message,
    });
  }
  process.stderr.write('.');
}
process.stderr.write('\n');

const passed = rows.filter(r => r.ok).length;
const rate = passed / rows.length;
const failures = rows.filter(r => !r.ok);
const network = rows.filter(r => r.source === 'network');
const avg = (xs: number[]) => (xs.length ? Math.round(xs.reduce((a, b) => a + b, 0) / xs.length) : 0);
const pct = (n: number) => `${(n * 100).toFixed(1)}%`;

// An offline run is only meaningful if the cache was already warm.
const ok = OFFLINE
  ? failures.length === 0
  : rate >= PASS_RATE && network.every(r => r.ok);

const origin = OFFLINE ? 'cache only (forced offline)' : WARM ? 'warm cache' : 'cold cache';
const networkFailures = failures.filter(r => r.source === 'network');

console.log(`\n${passed}/${rows.length} words resolved (${pct(rate)}) via ${origin}`);
console.log(`avg latency: overall ${avg(rows.map(r => r.ms))}ms, network ${avg(network.map(r => r.ms))}ms`);
console.log(`etymology present: ${rows.filter(r => r.hasOrigin).length}/${rows.length}`);
if (networkFailures.length) {
  console.log(`\nuser-visible network failures (${networkFailures.length}):`);
  for (const f of networkFailures.slice(0, 20)) console.log(`  ${f.word}: ${f.error} (${f.ms}ms)`);
}
console.log(ok ? '\nPASS' : '\nFAIL');

if (!WARM && !OFFLINE) {
  probeDictApi();
  mkdirSync('docs', { recursive: true });
  const stamp = new Date().toISOString();
  const table = failures.length
    ? `\n## Failures\n\n| word | ms | error |\n|---|---|---|\n${failures.map(f => `| ${f.word} | ${f.ms} | ${f.error} |`).join('\n')}\n`
    : '\nNo failures.\n';
  writeFileSync('docs/lookup-harness-report.md', `# Lookup reliability report

Generated by \`npx tsx scripts/lookup-harness.ts\` (${stamp}).

- Corpus: ${rows.length} common English words
- Resolved: ${passed}/${rows.length} (${pct(rate)}), threshold ${pct(PASS_RATE)}
- User-visible network failures: ${networkFailures.length}
- Average latency: ${avg(rows.map(r => r.ms))}ms overall, ${avg(network.map(r => r.ms))}ms uncached
- Etymology present: ${rows.filter(r => r.hasOrigin).length}/${rows.length}
- Result: **${ok ? 'PASS' : 'FAIL'}**
${table}
Re-run three consecutive times to confirm stability.
`);
  console.log('wrote docs/lookup-harness-report.md');
}

process.exit(ok ? 0 : 1);
